version: '3.8'

services:
  # Nginx Service
  nginx:
    build:
      context: ./build/nginx
      dockerfile: Dockerfile
    container_name: news_aggregator_nginx
    ports:
      - "8080:80"
    volumes:
      - ./src:/var/www/html
      - ./build/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
      - mysql
    networks:
      - news_aggregator_network
    restart: unless-stopped

  # PHP Service
  php:
    build:
      context: ./build/php
      dockerfile: Dockerfile
    container_name: news_aggregator_php
    volumes:
      - ./src:/var/www/html
    environment:
      - DB_CONNECTION=mysql
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_DATABASE=${DB_NAME}
      - DB_USERNAME=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
    depends_on:
      - mysql
    networks:
      - news_aggregator_network
    restart: unless-stopped

  # MySQL Service
  mysql:
    build:
      context: ./build/mysql
      dockerfile: Dockerfile
    container_name: news_aggregator_db
    environment:
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
    volumes:
      - mysql_data:/var/lib/mysql
      - ./build/mysql/my.cnf:/etc/mysql/conf.d/custom.cnf
      - ./build/mysql/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "3307:3306"
    networks:
      - news_aggregator_network
    restart: unless-stopped
    command: --default-authentication-plugin=mysql_native_password

  # Queue Worker Service
  queue:
    build:
      context: ./build/php
      dockerfile: Dockerfile
    container_name: news_aggregator_queue
    command: php artisan queue:work --tries=3 --timeout=90
    volumes:
      - ./src:/var/www/html
    environment:
      - DB_CONNECTION=mysql
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_DATABASE=${DB_NAME}
      - DB_USERNAME=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
    depends_on:
      - mysql
    networks:
      - news_aggregator_network
    restart: unless-stopped

volumes:
  mysql_data:
    driver: local

networks:
  news_aggregator_network:
    driver: bridge